insecure-entitlements=["network.host", "security.insecure"]

[registry."docker.io"]
mirrors = ["https://docker.1ms.run"]

[registry."git.service.home"]
http = true
insecure = true

[registry."git.service.home:80"]
http = true
insecure = true

[registry."git.service.home:443"]
http = true
insecure = true