name: Build UV Project

on:
  push:
    paths:
      - "uv-mini-demo/**" # 只有这个目录变动才触发

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 只需要这一步，uv 的所有魔法都在 Dockerfile 里完成了
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./uv-mini-demo
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/uv-mini-demo:latest
